collections_config:
  pages:
    path: ''
    icon: wysiwyg
    url: /

data_config:
  hero:
    path: /hero.json
    icon: title
  metadata:
    path: /metadata.json
    icon: info
  product:
    path: /product.json
    icon: list
  features:
    path: /features.json
    icon: check_circle
  footer:
    path: /footer.json
    icon: link
