collections_config:
  pages:
    path: ''
    icon: wysiwyg
    url: /

# Voeg dit gedeelte toe:
data_config:
  hero:
    path: hero.json
    icon: title
  metadata:
    path: metadata.json
    icon: info
