collections_config:
  pages:
    path: ''
    name: Homepage
    icon: wysiwyg
    url: /
    filter:
      exclude:
        # 1. Verberg de mappen die je niet wilt zien
        - collection
        - collection/*
        - components
        - components/*
        - node_modules
        - dist
        - public
        
        # 2. Verberg specifieke technische bestanden (maar NIET je content json's)
        - package.json
        - package-lock.json
        - tsconfig.json
        - metadata.json
        - vite.config.ts
        - cloudcannon.config.yml
        - '*.ts'
        - '*.js'
        - '*.md'
        - .gitignore

data_config:
  hero:
    path: /hero.json
    icon: title
  metadata:
    path: /metadata.json
    icon: info
  product:
    path: /product.json
    icon: list
  features:
    path: /features.json
    icon: check_circle
  footer:
    path: /footer.json
    icon: link
