collections_config:
  pages:
    path: ''
    name: Homepage
    icon: wysiwyg
    url: /
    filter:
      include:
        - index.html
      exclude:
        - collection
        - collection/**/*
        - components
        - components/**/*
        - node_modules
        - dist
        - public
        - package.json
        - package-lock.json
        - tsconfig.json
        - metadata.json
        - vite.config.ts
        - cloudcannon.config.yml
        - '*.ts'
        - '*.js'
        - '*.md'
        - .gitignore

  global_data:
    path: data/global
    name: Global Elements
    icon: public
    
  page_content:
    path: data/pages
    name: Page Content
    icon: notes

data_config:
  hero:
    path: data/pages/home/hero.json
  product:
    path: data/pages/home/product.json
  features:
    path: data/pages/home/features.json
  footer:
    path: data/global/footer.json
